// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoulChat.Infrastructure.Persistence;

#nullable disable

namespace SoulChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoulChat.Domain.Entities.AppChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("app_channel", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.AuditoriaCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("campo");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("RegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tabla_afectada");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("TablaAfectada", "RegistroId");

                    b.ToTable("auditoria_cambios", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Bsp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("bsp", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Linea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("CoordinadorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordinador_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescripcionUso")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_uso");

                    b.Property<int?>("ProgramadorId")
                        .HasColumnType("integer")
                        .HasColumnName("programador_id");

                    b.Property<int?>("StatusDesarrolloId")
                        .HasColumnType("integer")
                        .HasColumnName("status_desarrollo_id");

                    b.Property<int?>("TenenciaSimCardId")
                        .HasColumnType("integer")
                        .HasColumnName("tenencia_sim_card_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("ProgramadorId");

                    b.HasIndex("StatusDesarrolloId");

                    b.HasIndex("TenenciaSimCardId");

                    b.ToTable("lineas", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.LineaConnectlyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ApiKeyCifrada")
                        .HasColumnType("bytea")
                        .HasColumnName("api_key_cifrada");

                    b.Property<string>("BusinessId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("business_id");

                    b.Property<byte[]>("ContrasenaCifrada")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("contrasena_cifrada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dns")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("dns");

                    b.Property<int>("LineaId")
                        .HasColumnType("integer")
                        .HasColumnName("linea_id");

                    b.Property<string>("NumeroConnectly")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_connectly");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario");

                    b.Property<string>("Webhook")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("webhook");

                    b.HasKey("Id");

                    b.HasIndex("LineaId")
                        .IsUnique();

                    b.HasIndex("NumeroConnectly")
                        .IsUnique();

                    b.ToTable("linea_connectly_config", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.LineaSmartConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("app_channel_id");

                    b.Property<string>("BotId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bot_id");

                    b.Property<string>("BotVersion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("bot_version");

                    b.Property<int?>("BspId")
                        .HasColumnType("integer")
                        .HasColumnName("bsp_id");

                    b.Property<byte[]>("ClaveCifrada")
                        .HasColumnType("bytea")
                        .HasColumnName("clave_cifrada");

                    b.Property<string>("CompanyBot")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("company_bot");

                    b.Property<string>("CompanyCampanasBotai")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("company_campanas_botai");

                    b.Property<string>("CompanyIdCampanas")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_id_campanas");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnvioPush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("envio_push");

                    b.Property<bool>("Facturado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("facturado");

                    b.Property<DateOnly?>("FechaVerificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_verificacion");

                    b.Property<int>("LineaId")
                        .HasColumnType("integer")
                        .HasColumnName("linea_id");

                    b.Property<string>("NumeroLinea")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_linea");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int?>("TipoActivacionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_activacion_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uso")
                        .HasColumnType("text")
                        .HasColumnName("uso");

                    b.Property<string>("UsuarioCompanyId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_companyid");

                    b.Property<string>("WebhookCos")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("webhook_cos");

                    b.Property<string>("WebhookSda")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("webhook_sda");

                    b.HasKey("Id");

                    b.HasIndex("AppChannelId");

                    b.HasIndex("BspId");

                    b.HasIndex("LineaId")
                        .IsUnique();

                    b.HasIndex("NumeroLinea")
                        .IsUnique();

                    b.HasIndex("TipoActivacionId");

                    b.ToTable("linea_smart_config", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.StatusDesarrollo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("status_desarrollo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "En desarrollo"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Producción"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pausado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.TenenciaSimCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tenencia_sim_card", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "SIM física propia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Número IVR"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Número digital Connectly"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Número digital Smart"
                        });
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.TipoActivacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipo_activacion", (string)null);
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios_sistema", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@soulchat.local",
                            PasswordHash = "$2a$11$zceyATz3nshERAyWCQdsheStsMEiMtGxh/RGhiacwUSjPGiMTeouG",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.AuditoriaCambio", b =>
                {
                    b.HasOne("SoulChat.Domain.Entities.UsuarioSistema", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Linea", b =>
                {
                    b.HasOne("SoulChat.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Lineas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoulChat.Domain.Entities.Empleado", "Coordinador")
                        .WithMany("LineasComoCoordinador")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulChat.Domain.Entities.Empleado", "Programador")
                        .WithMany("LineasComoProgramador")
                        .HasForeignKey("ProgramadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulChat.Domain.Entities.StatusDesarrollo", "StatusDesarrollo")
                        .WithMany("Lineas")
                        .HasForeignKey("StatusDesarrolloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulChat.Domain.Entities.TenenciaSimCard", "TenenciaSimCard")
                        .WithMany("Lineas")
                        .HasForeignKey("TenenciaSimCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Coordinador");

                    b.Navigation("Programador");

                    b.Navigation("StatusDesarrollo");

                    b.Navigation("TenenciaSimCard");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.LineaConnectlyConfig", b =>
                {
                    b.HasOne("SoulChat.Domain.Entities.Linea", "Linea")
                        .WithOne("ConnectlyConfig")
                        .HasForeignKey("SoulChat.Domain.Entities.LineaConnectlyConfig", "LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.LineaSmartConfig", b =>
                {
                    b.HasOne("SoulChat.Domain.Entities.AppChannel", "AppChannel")
                        .WithMany("LineaSmartConfigs")
                        .HasForeignKey("AppChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulChat.Domain.Entities.Bsp", "Bsp")
                        .WithMany("LineaSmartConfigs")
                        .HasForeignKey("BspId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulChat.Domain.Entities.Linea", "Linea")
                        .WithOne("SmartConfig")
                        .HasForeignKey("SoulChat.Domain.Entities.LineaSmartConfig", "LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulChat.Domain.Entities.TipoActivacion", "TipoActivacion")
                        .WithMany("LineaSmartConfigs")
                        .HasForeignKey("TipoActivacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppChannel");

                    b.Navigation("Bsp");

                    b.Navigation("Linea");

                    b.Navigation("TipoActivacion");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.AppChannel", b =>
                {
                    b.Navigation("LineaSmartConfigs");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Bsp", b =>
                {
                    b.Navigation("LineaSmartConfigs");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("LineasComoCoordinador");

                    b.Navigation("LineasComoProgramador");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.Linea", b =>
                {
                    b.Navigation("ConnectlyConfig");

                    b.Navigation("SmartConfig");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.StatusDesarrollo", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.TenenciaSimCard", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SoulChat.Domain.Entities.TipoActivacion", b =>
                {
                    b.Navigation("LineaSmartConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
