namespace SoulChat.Application.DTOs.Smart;

public record SmartCreateDto(
    string NumeroLinea,
    string? Estado,
    string? TipoActivacion,
    string? CompanyCampanasBotai,
    int? BspId,
    string? WebhookCampanas,
    string? WebhookCos,
    string? WebhookSda,
    string? UsuarioCompanyId,
    string? Clave,
    string? CompanyBot,
    string? BotId,
    string? BotVersion,
    string? AppChannel,
    string? CompanyIdCampanas,
    bool EnvioPush,
    string? Uso,
    string? Observaciones,
    DateOnly? FechaVerificacion,
    bool Facturado);

public record SmartUpdateDto(
    string NumeroLinea,
    string? Estado,
    string? TipoActivacion,
    string? CompanyCampanasBotai,
    int? BspId,
    string? WebhookCampanas,
    string? WebhookCos,
    string? WebhookSda,
    string? UsuarioCompanyId,
    string? Clave,
    string? CompanyBot,
    string? BotId,
    string? BotVersion,
    string? AppChannel,
    string? CompanyIdCampanas,
    bool EnvioPush,
    string? Uso,
    string? Observaciones,
    DateOnly? FechaVerificacion,
    bool Facturado);

public record SmartResponseDto(
    int Id,
    int LineaId,
    string NumeroLinea,
    string? Estado,
    string? TipoActivacion,
    string? CompanyCampanasBotai,
    int? BspId,
    string? BspNombre,
    string? WebhookCampanas,
    string? WebhookCos,
    string? WebhookSda,
    string? UsuarioCompanyId,
    string? ClaveMasked,
    string? CompanyBot,
    string? BotId,
    string? BotVersion,
    string? AppChannel,
    string? CompanyIdCampanas,
    bool EnvioPush,
    string? Uso,
    string? Observaciones,
    DateOnly? FechaVerificacion,
    bool Facturado,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record SmartRevealResponseDto(string? Clave);
